version: '3.3'
##########################
# LME Stack deploy file  #
# Version 0.1 - 27/03/19 #
##########################
services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment:
      - cluster.name=loggingmadeeasy-es
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xmsram-countg -Xmxram-countg"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    secrets:
      - source: elasticsearch.keystore
        target: /usr/share/elasticsearch/config/elasticsearch.keystore
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - elasticsearch.username="kibana"
      - elasticsearch.password="kibanapassword"
    networks:
      - esnet
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    environment:
      - elasticsearch.username=logstash_system
    ports:
      - 5044:5044 
    networks:
      - esnet
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
        mode: 0444
      - source: osmap.csv
        target: /tmp/osmap.csv
        mode: 0444
    secrets:
      - ca.crt
      - logstash.crt
      - logstash.key


secrets:
  ca.crt:
    external: true
  logstash.crt:
    external: true
  logstash.key:
    external: true
  elasticsearch.keystore:
    external: true

configs:
  logstash.conf:
    external: true
  osmap.csv:
    external: true
      
volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: overlay     
     

